import type { CmsGuideTable } from "./types";

// Generic / fallback guides. Every deliverable must have an entry here so unknown CMSs degrade gracefully.
export const GENERIC_GUIDES: CmsGuideTable = {
  title_tag: {
    deliverable: "title_tag",
    platform: "generic",
    title: "Update the page title tag",
    estimatedMinutes: 3,
    steps: [
      { text: "Log into your website's CMS or page editor." },
      { text: "Navigate to the page at this URL.", copyable: { label: "Page URL", valueKey: "page_url" } },
      { text: "Find the SEO settings panel for this page (often labeled 'SEO', 'Meta', 'Search Appearance', or 'Page Properties')." },
      { text: "Replace the existing browser title / SEO title with the new value below.", copyable: { label: "New title tag", valueKey: "proposed_value" } },
      { text: "Save and publish the page." },
      { text: "Open an incognito tab and view-source the page to confirm <title> reflects the new value." },
    ],
  },
  meta_description: {
    deliverable: "meta_description",
    platform: "generic",
    title: "Update the meta description",
    estimatedMinutes: 3,
    steps: [
      { text: "Log into your CMS and open the page editor.", copyable: { label: "Page URL", valueKey: "page_url" } },
      { text: "Find the SEO panel (often 'Search Appearance', 'Meta', or 'SEO settings')." },
      { text: "Paste this into the meta description field.", copyable: { label: "New meta description", valueKey: "proposed_value" } },
      { text: "Save and publish.", warning: "Some CMSs cache the meta description — clear cache if changes don't appear in view-source." },
    ],
  },
  h1: {
    deliverable: "h1",
    platform: "generic",
    title: "Update the H1 heading",
    estimatedMinutes: 4,
    steps: [
      { text: "Open the page in your CMS editor.", copyable: { label: "Page URL", valueKey: "page_url" } },
      { text: "Locate the main heading at the top of the page (usually the largest text — H1 element)." },
      { text: "Replace the heading text with this:", copyable: { label: "New H1", valueKey: "proposed_value" } },
      { text: "Confirm only one H1 exists on the page (this should be the main heading, not a section heading)." },
      { text: "Save and publish." },
    ],
  },
  internal_link_insertion: {
    deliverable: "internal_link_insertion",
    platform: "generic",
    title: "Add an internal link",
    estimatedMinutes: 4,
    steps: [
      { text: "Open the source page in your CMS editor.", copyable: { label: "Source page", valueKey: "page_url" } },
      { text: "Find the paragraph containing this text:", copyable: { label: "Source paragraph", valueKey: "source_paragraph_text" } },
      { text: "Highlight this anchor text within that paragraph:", copyable: { label: "Anchor text", valueKey: "anchor_text" } },
      { text: "Apply a link with this destination URL:", copyable: { label: "Link target", valueKey: "target_url" } },
      { text: "Save and publish the page." },
    ],
  },
  content_rewrite: {
    deliverable: "content_rewrite",
    platform: "generic",
    title: "Apply the content rewrite",
    estimatedMinutes: 10,
    steps: [
      { text: "Open the page in your CMS editor.", copyable: { label: "Page URL", valueKey: "page_url" } },
      { text: "Replace the matching section with the new content from the brief." },
      { text: "Use the 'before' value to find the exact section.", copyable: { label: "Find this", valueKey: "current_value" } },
      { text: "Replace it with this:", copyable: { label: "Replace with", valueKey: "proposed_value" } },
      { text: "Save and publish." },
    ],
  },
  content_block_insert: {
    deliverable: "content_block_insert",
    platform: "generic",
    title: "Insert a new content block",
    estimatedMinutes: 6,
    steps: [
      { text: "Open the page in your CMS editor.", copyable: { label: "Page URL", valueKey: "page_url" } },
      { text: "Insert this content block at the location specified in the recommendation:" , copyable: { label: "New content", valueKey: "proposed_value" } },
      { text: "Save and publish.", warning: "Most CMSs require pasting as plain text or HTML — check the formatting matches surrounding content." },
    ],
  },
  full_article_publish: {
    deliverable: "full_article_publish",
    platform: "generic",
    title: "Publish the article on your CMS",
    estimatedMinutes: 12,
    steps: [
      { text: "In your CMS, create a new blog post / article." },
      { text: "Set the post title to:", copyable: { label: "Post title", valueKey: "meta_title" } },
      { text: "Set the URL slug to:", copyable: { label: "Slug", valueKey: "slug" } },
      { text: "Paste the article body (HTML).", copyable: { label: "Article HTML", valueKey: "html_body" } },
      { text: "Set the meta description.", copyable: { label: "Meta description", valueKey: "meta_description" } },
      { text: "Add a featured image (use any relevant image from your media library)." },
      { text: "Set the post category and tags as appropriate." },
      { text: "Publish or schedule the post for the agreed date." },
    ],
  },
  schema_org: {
    deliverable: "schema_org",
    platform: "generic",
    title: "Add structured data (JSON-LD)",
    estimatedMinutes: 8,
    steps: [
      { text: "Open the page in your CMS editor.", copyable: { label: "Page URL", valueKey: "page_url" } },
      { text: "Find the option to inject custom HTML/JavaScript into the page <head>. Some CMSs call this 'Custom Code', 'Header Snippets', or 'Page Code Injection'." },
      { text: "Paste this JSON-LD script tag:", copyable: { label: "JSON-LD", valueKey: "proposed_value" } },
      { text: "Save and publish." },
      { text: "Validate at https://search.google.com/test/rich-results — paste the page URL and confirm no errors." },
    ],
  },
  faq_schema: {
    deliverable: "faq_schema",
    platform: "generic",
    title: "Add FAQ schema and visible FAQ section",
    estimatedMinutes: 10,
    steps: [
      { text: "Open the page in your CMS editor.", copyable: { label: "Page URL", valueKey: "page_url" } },
      { text: "Add a visible FAQ section to the page using your CMS's accordion or text blocks. The questions and answers must match what's in the schema below." },
      { text: "In the page <head> code injection area, paste this JSON-LD:", copyable: { label: "FAQ JSON-LD", valueKey: "proposed_value" }, warning: "FAQ schema is only valid if the questions and answers also appear visibly on the page." },
      { text: "Save and publish, then validate at https://search.google.com/test/rich-results." },
    ],
  },
  location_signals: {
    deliverable: "location_signals",
    platform: "generic",
    title: "Add local business / location signals",
    estimatedMinutes: 8,
    steps: [
      { text: "Open the page in your CMS editor.", copyable: { label: "Page URL", valueKey: "page_url" } },
      { text: "Add LocalBusiness JSON-LD to the page <head>:", copyable: { label: "LocalBusiness JSON-LD", valueKey: "proposed_value" } },
      { text: "Verify your address and hours match what's listed on your Google Business Profile." },
      { text: "Save and publish, then validate at https://search.google.com/test/rich-results." },
    ],
  },
  redirect: {
    deliverable: "redirect",
    platform: "generic",
    title: "Set up a 301 redirect",
    estimatedMinutes: 5,
    steps: [
      { text: "Find your CMS's redirect manager (often under SEO settings, or a plugin called 'Redirects' / 'URL Redirects')." },
      { text: "Create a new 301 (permanent) redirect from this source path:", copyable: { label: "From", valueKey: "current_value" } },
      { text: "To this destination:", copyable: { label: "To", valueKey: "proposed_value" } },
      { text: "Save the redirect." },
      { text: "Test by visiting the source URL in an incognito window — it should redirect to the destination.", warning: "Use 301 (permanent), not 302 (temporary)." },
    ],
  },
  canonical: {
    deliverable: "canonical",
    platform: "generic",
    title: "Set the canonical URL",
    estimatedMinutes: 4,
    steps: [
      { text: "Open the page in your CMS editor.", copyable: { label: "Page URL", valueKey: "page_url" } },
      { text: "Find the SEO panel and locate the canonical URL field (sometimes called 'Canonical', 'rel=canonical', or 'Custom canonical URL')." },
      { text: "Set it to this value:", copyable: { label: "Canonical URL", valueKey: "proposed_value" } },
      { text: "Save and publish." },
      { text: "View-source the page and confirm <link rel=\"canonical\"> matches." },
    ],
  },
  alt_text: {
    deliverable: "alt_text",
    platform: "generic",
    title: "Add alt text to an image",
    estimatedMinutes: 2,
    steps: [
      { text: "Find the image referenced at this URL.", copyable: { label: "Page URL", valueKey: "page_url" } },
      { text: "Open the image in your media library or page editor and update the alt text field." },
      { text: "Use this alt text:", copyable: { label: "Alt text", valueKey: "proposed_value" } },
      { text: "Save the image / page." },
    ],
  },
  robots_txt: {
    deliverable: "robots_txt",
    platform: "generic",
    title: "Update robots.txt",
    estimatedMinutes: 5,
    steps: [
      { text: "Find your CMS's robots.txt management (often under SEO settings or hosting/server config)." },
      { text: "Update the file to this content:", copyable: { label: "robots.txt", valueKey: "proposed_value" } },
      { text: "Save the file.", warning: "After saving, visit yourdomain.com/robots.txt in an incognito window to confirm the changes are live." },
    ],
  },
  sitemap_xml: {
    deliverable: "sitemap_xml",
    platform: "generic",
    title: "Update the XML sitemap",
    estimatedMinutes: 5,
    steps: [
      { text: "Most CMSs and SEO plugins generate the sitemap automatically. Confirm yours does." },
      { text: "If manual: update the sitemap file to include or exclude the URLs in the recommendation.", copyable: { label: "Recommended changes", valueKey: "proposed_value" } },
      { text: "Submit the updated sitemap URL in Google Search Console under Sitemaps." },
    ],
  },
  indexation_submit: {
    deliverable: "indexation_submit",
    platform: "generic",
    title: "Request indexation in Google Search Console",
    estimatedMinutes: 3,
    steps: [
      { text: "Go to https://search.google.com/search-console and select your property." },
      { text: "Use the URL Inspection tool at the top — paste the URL.", copyable: { label: "URL to submit", valueKey: "page_url" } },
      { text: "Click 'Test Live URL' to confirm the page can be crawled." },
      { text: "Click 'Request Indexing'.", warning: "Google rate-limits this to roughly ~10 URL requests per day per property." },
    ],
  },
};
