import type { Page, SiteContext } from "../types";

/** Build a page row with sane defaults; override what you need. */
export function makePage(overrides: Partial<Page> = {}): Page {
  return {
    id: overrides.id ?? "page-1",
    url: overrides.url ?? "https://example.com/about",
    status_code: 200,
    redirect_target: null,
    redirect_chain: null,
    response_time_ms: 500,
    rendered_html_size: 50_000,
    is_https: true,
    mixed_content_count: 0,
    title: "About Example — A Concise Descriptive Title",
    title_length: 46,
    meta_description: "A descriptive meta that summarizes the page in roughly one hundred and twenty characters total length, fitting nicely.",
    meta_description_length: 117,
    h1_text: "About Example",
    h1_count: 1,
    h2_count: 3,
    h3_count: 2,
    headings: [
      { level: 1, text: "About Example" },
      { level: 2, text: "Our story" },
      { level: 3, text: "Founded" },
    ],
    has_skipped_heading_level: false,
    canonical_url: overrides.url ?? "https://example.com/about",
    canonical_self_referencing: true,
    canonical_status_code: 200,
    is_indexable: true,
    noindex: false,
    nofollow: false,
    in_sitemap: true,
    schema_types: ["WebPage"],
    schema_blocks: [{ "@type": "WebPage", name: "About" }],
    schema_invalid_count: 0,
    og_title: "About Example",
    og_description: "About us",
    og_image: "https://example.com/og.png",
    og_image_status: 200,
    og_type: "website",
    twitter_card: "summary_large_image",
    hreflang_tags: null,
    hreflang_invalid: false,
    internal_links_out: 8,
    internal_links_in: 5,
    external_links_out: 2,
    broken_links_out: [],
    generic_anchor_count: 0,
    unsafe_blank_target_count: 0,
    click_depth: 1,
    word_count: 600,
    text_to_html_ratio: 0.25,
    content_hash: "abc123",
    duplicate_of_url: null,
    images_count: 3,
    alt_text_missing_count: 0,
    alt_text_empty_count: 0,
    alt_text_too_long_count: 0,
    alt_text_filename_count: 0,
    alt_text_duplicate_count: 0,
    placeholder_text_found: [],
    unsubstituted_vars: [],
    has_faq_format: false,
    has_numbered_steps: false,
    has_table_without_header: false,
    has_single_item_list: false,
    date_published: null,
    date_modified: null,
    has_author: true,
    has_table_of_contents: false,
    page_type: "other",
    is_nav_page: false,
    ...overrides,
  };
}

export function makeSite(overrides: Partial<SiteContext> = {}): SiteContext {
  return {
    root_url: "https://example.com",
    robots_txt_present: true,
    robots_txt_content: "User-agent: *\nAllow: /\nSitemap: https://example.com/sitemap.xml",
    sitemap_present: true,
    sitemap_urls: ["https://example.com/", "https://example.com/about"],
    llms_txt_present: true,
    llms_full_txt_present: true,
    https_enforced: true,
    hsts_header_present: true,
    ...overrides,
  };
}

export function ctxFor(page: Page, site = makeSite(), allPages: Page[] = [page]) {
  return { allPages, site };
}
