-- Run this in Supabase SQL editor:
-- https://supabase.com/dashboard/project/grjxnquhrdamncnmjftw/sql/new

CREATE TABLE IF NOT EXISTS reports (
  id                        UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  client_id                 TEXT NOT NULL,
  month                     INTEGER NOT NULL,
  report_month_label        TEXT NOT NULL,
  report_generated_at       TIMESTAMPTZ DEFAULT NOW(),
  changes_made              INTEGER DEFAULT 0,
  changes_by_category       JSONB,
  notable_changes           TEXT,
  skipped_count             INTEGER DEFAULT 0,
  pages_optimized           JSONB,
  schema_types_added        JSONB,
  internal_links_added      INTEGER,
  approval_queue_status     JSONB,
  gsc_clicks_this           INTEGER,
  gsc_clicks_prior          INTEGER,
  gsc_clicks_delta          INTEGER,
  gsc_clicks_pct            TEXT,
  gsc_impressions_this      INTEGER,
  gsc_impressions_prior     INTEGER,
  gsc_impressions_delta     INTEGER,
  gsc_avg_position_this     NUMERIC(6,2),
  gsc_avg_position_prior    NUMERIC(6,2),
  gsc_avg_position_delta    NUMERIC(6,2),
  gsc_ctr_this              NUMERIC(6,4),
  gsc_ctr_prior             NUMERIC(6,4),
  gsc_3month_trend          JSONB,
  top_ranking_gains         JSONB,
  top_ranking_losses        JSONB,
  new_top_20_keywords       JSONB,
  top_1_3_keywords          JSONB,
  top_pages_growth          JSONB,
  top_pages_loss            JSONB,
  ga4_sessions_this         INTEGER,
  ga4_sessions_prior        INTEGER,
  ga4_sessions_delta        INTEGER,
  ga4_users_this            INTEGER,
  ga4_users_prior           INTEGER,
  ga4_users_delta           INTEGER,
  ga4_ai_sessions_this      INTEGER,
  ga4_ai_sessions_prior     INTEGER,
  ga4_ai_sessions_delta     INTEGER,
  ga4_ai_by_source          JSONB,
  articles_published        JSONB,
  articles_now_ranking      JSONB,
  faqs_live                 JSONB,
  content_in_queue          JSONB,
  ai_mentions               JSONB,
  entity_coverage_score     INTEGER,
  entity_coverage_prior     INTEGER,
  faq_schema_coverage_pct   INTEGER,
  narrative                 TEXT,
  next_month_priorities     TEXT,
  created_at                TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS reports_client_id_idx  ON reports(client_id);
CREATE INDEX IF NOT EXISTS reports_generated_idx  ON reports(report_generated_at DESC);
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;
